<a href="https://colab.research.google.com/github/2303A52492/23CSBTB50/blob/main/Arrays.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
np.array([1,2,3])
np.array([[1,2,3],[4,5,6],[7,8,9]])

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [5]:
import numpy as np
import pandas as pd

# Numpy Arrays
arr1 = np.array([1, 2, 3, 4, 5])  # 1D array
arr2 = np.array([[1, 2, 3], [4, 5, 6]])  # 2D array

# Pandas Series (1D labeled array)
series1 = pd.Series([10, 20, 30, 40, 50], index=['a', 'b', 'c', 'd', 'e'])

# Pandas DataFrame (2D labeled data structure)
data = {'Name': ['Alice', 'Bob', 'Charlie'], 'Age': [25, 30, 28]}
df = pd.DataFrame(data)

print("Numpy Array 1:\n", arr1)
print("\nNumpy Array 2:\n", arr2)
print("\nPandas Series:\n", series1)
print("\nPandas DataFrame:\n", df)

Numpy Array 1:
 [1 2 3 4 5]

Numpy Array 2:
 [[1 2 3]
 [4 5 6]]

Pandas Series:
 a    10
b    20
c    30
d    40
e    50
dtype: int64

Pandas DataFrame:
       Name  Age
0    Alice   25
1      Bob   30
2  Charlie   28


In [2]:
import numpy as np

a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

addition = a + b

# Subtraction
subtraction = a - b

# Multiplication (element-wise)
multiplication = a * b

# Division (element-wise)
division = a / b

print("Addition: ", addition)
print("Subtraction: ", subtraction)
print("Multiplication: ", multiplication)
print("Division: ", division)

Addition:  [5 7 9]
Subtraction:  [-3 -3 -3]
Multiplication:  [ 4 10 18]
Division:  [0.25 0.4  0.5 ]


In [3]:
import numpy as np


matrix_1x1 = np.array([[1]])


matrix_2x2 = np.array([[1, 2],
                       [3, 4]])


matrix_3x3 = np.array([[1, 2, 3],
                       [4, 5, 6],
                       [7, 8, 9]])

print("1x1 Matrix:\n", matrix_1x1)
print("\n2x2 Matrix:\n", matrix_2x2)
print("\n3x3 Matrix:\n", matrix_3x3)

1x1 Matrix:
 [[1]]

2x2 Matrix:
 [[1 2]
 [3 4]]

3x3 Matrix:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]


In [4]:
import numpy as np


matrix1 = np.array([[1, 2],
                    [3, 4]])

matrix2 = np.array([[5, 6],
                    [7, 8]])

result = np.dot(matrix1, matrix2)

print("Result of matrix multiplication:\n", result)

Result of matrix multiplication:
 [[19 22]
 [43 50]]
